Name: User Configuration for Sizing Tool
Comments: Entered values will overwrite values in default configuration.

### SIZING TOOL SETTINGS ###
Sizing_Params:
    LifetimeSplits: 3  # Number of lifetime splits (with diff. storage unit aging) considered for HESS cost approximation
    Num_price_days: 12  # Number of representative daily price time series used to approximate HESS cost for current capacities
    Num_freq_days: 1  # Number of representative daily frequency time series used in the simulation of one day
    UseParallel: True  # If True, schedule optimization for the representative days will be done using parallel processing
    Max_iterations: 1000  # Maximum number of iterations for finding optimal storage unit sizes
    Stepsize: 0.01  # Step size for updating the storage unit capacities based on the gradients
    Tolerance: 0.001  # Tolerance for gradient below which the solution is accepted and sizing iteration interrupted
    Delta_x: 0.01  # Modification of a capacity in the perturbation
    Parameterization_granularity: 8  # Number of pRt values in the pRt range used for calc. loss & degr.cost coefficients
    Price_day_weighting: [0.04657534246575343,  # Occurrence weights for representative daily prices time series
                          0.03287671232876712,  # Must match the order of price files in InputData/Prices (price_day1.csv,...)
                          0.2328767123287671,   # Must sum up to 1
                          0.16712328767123288,  # Must be larger or equal Num_price_days
                          0.049315068493150684,
                          0.00821917808219178,
                          0.136986301369863,
                          0.18082191780821918,
                          0.10410958904109589,
                          0.03561643835616438,
                          0.0027397260273972603,
                          0.0027397260273972603]
    Frequency_day_weighting: [0.5,  # Occurrence weights for representative daily frequency time series
                              0.5,  # Must match order of frequency files in InputData/Frequency (frequency_day1.csv,...)
                              0,  # Must sum up to 1
                              0,]  # Must be larger or equal Num_freq_days

### HESS SETTINGS ###
HESS_Params:
    HESS_score: 1  # TODO Service delivery score of the HESS???
    Kappa: 0.25  # Maximum duration of the regulation reserve in hours (15 min)  # TODO should probably match Power_reserve_period?
    Zeta: 1  # Coefficient for conservative sustained duration (if > 1 less conservative)
    BudgetLimit: 10000  # Total budget limit for the HESS
    FixedCost: 0  # Fixed cost of for HESS installation
    Int_rate: 0.05  # Interest rate
    Lifetime: 10  # Expected lifetime of the HESS

### SIMULATION CONTROLLER SETTINGS ###
Controller:
  Class: "controllers.SizingToolController"  # Defines the controller which manages operation of storage units in simulation
  Parameters:  # Put static (i.e. not iterated) controller parameters here.

### STORAGE UNIT SETTINGS (relevant for simulation and sizing) ###
Storage_Units:
  - Lithium_Battery:
      # Sizing-only parameters
      Min_Limit_Energy_Capacity: 0.0001  # Minimum energy capacity [kWh]
      Max_Limit_Energy_Capacity: 40  # Maximum energy capacity [kWh]
      Min_Limit_Power: 0  # Minimum power capacity [kW]
      Max_Limit_Power: 15  # Maximum power capacity [kW]
      Eta_ch: 0.9  # Charging efficiency
      Eta_dis: 0.9  # Discharging efficiency
      Static: 0  # Idling loss fraction from current SOE during one hour [-]
      Gamma: 1  # ??
      PowerCapCost: 5000  # Cost for power capacity [€/kW]
      EnergyCapCost: 4000  # Cost for energy capacity [€/kWh]
      Deg_cost_per_kWh: 1000  # Cost for capacity degradation [€/kWh]
      # Simulation-only parameters
      Implementation: "simulators.NMCBatteryFirstLife"  # Model used in simulation
      Unit_Specific_Parameters:
        L_total: 0  # Current lifetime (0=new, 0.1=10% lifetime passed, ...)
      # Shared parameters
      Available_Capacity: 1  # Initial energy capacity [kWh]
      Available_Power: 1  # Initial power capacity [kW]
      Maximum_SOC: 90  # Maximum allowed SOC [%]
      Minimum_SOC: 10  # Minimum allowed SOC [%]
  - Super_Capacitor:
      # Sizing-only parameters
      Min_Limit_Energy_Capacity: 0.0001  # Minimum energy capacity [kWh]
      Max_Limit_Energy_Capacity: 0.5  # Maximum energy capacity [kWh]
      Min_Limit_Power: 0  # Minimum power capacity [kW]
      Max_Limit_Power: 15  # Maximum power capacity [kW]
      Eta_ch: 0.92  # Charging efficiency
      Eta_dis: 0.92  # Discharging efficiency
      Static: 0  # Idling loss fraction from current SOE during one hour [-]
      Gamma: 1  # ??
      PowerCapCost: 5000  # Cost for power capacity [€/kW]
      EnergyCapCost: 4000  # Cost for energy capacity [€/kWh]
      # Simulation-only parameters
      Implementation: "simulators.SuperCapacitor"  # Model used in simulation
      # Shared parameters
      Available_Capacity: 0.5  # Initial energy capacity [kWh]
      Available_Power: 1  # Initial power capacity [kW]
      Maximum_SOC: 90  # Maximum allowed SOC [%]
      Minimum_SOC: 10  # Minimum allowed SOC [%]
  - Vanadium_Battery:
      # Sizing-only parameters
      Min_Limit_Energy_Capacity: 0.0001  # Minimum energy capacity [kWh]
      Max_Limit_Energy_Capacity: 150  # Maximum energy capacity [kWh]
      Min_Limit_Power: 0  # Minimum power capacity [kW]
      Max_Limit_Power: 48  # Maximum power capacity [kW]
      Eta_ch: 0.7  # Charging efficiency
      Eta_dis: 0.7  # Discharging efficiency
      Static: 0  # Idling loss fraction from current SOE during one hour [-]
      Gamma: 1  # ??
      PowerCapCost: 5000  # Cost for power capacity [€/kW]
      EnergyCapCost: 4000  # Cost for energy capacity [€/kWh]
      # Simulation-only parameters
      Implementation: "simulators.VanadiumBattery"  # Model used in simulation
      # Shared parameters
      Available_Capacity: 1  # Initial energy capacity [kWh]
      Available_Power: 1  # Initial power capacity [kW]
      Maximum_SOC: 90  # Maximum allowed SOC [%]
      Minimum_SOC: 10  # Minimum allowed SOC [%]
