Name: User Configuration for Standalone Daily Schedule Optimization
Comments: Is a subset of Sizing Tool config files as only parameters relevant to daily schedule optimization are listed. 
          Note that price file and coefficients for losses and degradation cost have to be manually defined in contrast
          to the sizing tool. Can be determined by running the Standalone Parameterization for the same HESS configuration.

### DAILY SCHEDULE OPTIMIZATION SETTINGS ###
Sizing_Params:
    Price_file: "price_day12.csv"

HESS_Params:
    HESS_score: 1  # TODO Service delivery score of the HESS???
    Kappa: 0.25  # Maximum duration of the regulation reserve in hours (15 min)  # TODO should probably match Power_reserve_period?
    Zeta: 1  # Coefficient for conservative sustained duration (if > 1 less conservative)

Storage_Units:
  - Lithium_Battery:
      Eta_ch: 0.9  # Charging efficiency
      Eta_dis: 0.9  # Discharging efficiency
      Static: 0  # Idling loss fraction from current SOE during one hour [-]
      Gamma: 1  # ??
      Deg_cost_coef_a: 0.005  # Coefficient of quadratic representation of degradation cost(pRT)
      Deg_cost_coef_b: 0.005  # Coefficient of quadratic representation of degradation cost(pRT)
      Deg_cost_coef_c: 0.005  # Coefficient of quadratic representation of degradation cost(pRT)
      Loss_coef_a: 0.005  # Coefficient of linear representation of losses(pRT)
      Loss_coef_b: 0.005  # Coefficient of linear representation of losses(pRT)
      Available_Capacity: 1  # Initial energy capacity [kWh]
      Available_Power: 1  # Initial power capacity [kW]
      Maximum_SOC: 90  # Maximum allowed SOC [%]
      Minimum_SOC: 10  # Minimum allowed SOC [%]
  - Super_Capacitor:
      Eta_ch: 0.92  # Charging efficiency
      Eta_dis: 0.92  # Discharging efficiency
      Static: 0  # Idling loss fraction from current SOE during one hour [-]
      Gamma: 1  # ??
      Loss_coef_a: 0.005  # Coefficient of linear representation of losses(pRT)
      Loss_coef_b: 0.005  # Coefficient of linear representation of losses(pRT)
      Available_Capacity: 0.5  # Initial energy capacity [kWh]
      Available_Power: 1  # Initial power capacity [kW]
      Maximum_SOC: 90  # Maximum allowed SOC [%]
      Minimum_SOC: 10  # Minimum allowed SOC [%]
  - Vanadium_Battery:
      Eta_ch: 0.7  # Charging efficiency
      Eta_dis: 0.7  # Discharging efficiency
      Static: 0  # Idling loss fraction from current SOE during one hour [-]
      Gamma: 1  # ??
      Loss_coef_a: 0.005  # Coefficient of linear representation of losses(pRT)
      Loss_coef_b: 0.005  # Coefficient of linear representation of losses(pRT)
      Available_Capacity: 1  # Initial energy capacity [kWh]
      Available_Power: 1  # Initial power capacity [kW]
      Maximum_SOC: 90  # Maximum allowed SOC [%]
      Minimum_SOC: 10  # Minimum allowed SOC [%]
