Name: User Configuration for Standalone Daily Schedule Optimization
Comments: Is a subset of Sizing Tool config files as only parameters relevant to daily schedule optimization are listed. 
          Note that price file and coefficients for losses and degradation cost have to be manually defined in contrast
          to the sizing tool. Can be determined by running the Standalone Parameterization for the same HESS configuration.

### DAILY SCHEDULE OPTIMIZATION SETTINGS ###
Sizing_Params:
    Price_file: "price_day12.csv"

HESS_Params:
    Key:
    HESS_score: 1  # TODO Service delivery score of the HESS???
    Kappa: 0.25  # Maximum duration of the regulation reserve in hours (15 min)  # TODO should probably match Power_reserve_period?
    Zeta: 1  # Coefficient for conservative sustained duration (if > 1 less conservative)

Electrcial_Storage_Units:
  - Lithium_Battery:
      Key: 'BAT_ESSm'
      Eta_ch: 0.9  # Charging efficiency
      Eta_dis: 0.9  # Discharging efficiency
      Static: 0  # Idling loss fraction from current SOE during one hour [-]
      Gamma: 1  # ??
      Deg_cost_coef_a: 0.005  # Coefficient of quadratic representation of degradation cost(pRT)
      Deg_cost_coef_b: 0.005  # Coefficient of quadratic representation of degradation cost(pRT)
      Deg_cost_coef_c: 0.005  # Coefficient of quadratic representation of degradation cost(pRT)
      Loss_coef_a: 0.005  # Coefficient of linear representation of losses(pRT)
      Loss_coef_b: 0.005  # Coefficient of linear representation of losses(pRT)
      Available_Capacity: 1  # Initial energy capacity [kWh]
      Available_Power: 1  # Initial power capacity [kW]
      Maximum_SOC: 90  # Maximum allowed SOC [%]
      Minimum_SOC: 10  # Minimum allowed SOC [%]
  - Super_Capacitor:
      Key: 'SC_ESSm'
      Eta_ch: 0.92  # Charging efficiency
      Eta_dis: 0.92  # Discharging efficiency
      Static: 0  # Idling loss fraction from current SOE during one hour [-]
      Gamma: 1  # ??
      Loss_coef_a: 0.005  # Coefficient of linear representation of losses(pRT)
      Loss_coef_b: 0.005  # Coefficient of linear representation of losses(pRT)
      Available_Capacity: 0.5  # Initial energy capacity [kWh]
      Available_Power: 1  # Initial power capacity [kW]
      Maximum_SOC: 90  # Maximum allowed SOC [%]
      Minimum_SOC: 10  # Minimum allowed SOC [%]
  - Vanadium_Battery:
      Eta_ch: 0.7  # Charging efficiency
      Eta_dis: 0.7  # Discharging efficiency
      Static: 0  # Idling loss fraction from current SOE during one hour [-]
      Gamma: 1  # ??
      Loss_coef_a: 0.005  # Coefficient of linear representation of losses(pRT)
      Loss_coef_b: 0.005  # Coefficient of linear representation of losses(pRT)
      Available_Capacity: 1  # Initial energy capacity [kWh]
      Available_Power: 1  # Initial power capacity [kW]
      Maximum_SOC: 90  # Maximum allowed SOC [%]
      Minimum_SOC: 10  # Minimum allowed SOC [%]
  - Pumped_hydro_storage:
        Key: 'HP_ESSm'
        Eta_ch: 0.75  # Charging efficiency
        Eta_dis: 0.75  # Discharging efficiency
        Static: 0  # Idling loss fraction from current SOE during one hour [-]
        Gamma: 1  # ??
        Deg_cost_coef_a: 0.005  # Coefficient of quadratic representation of degradation cost(pRT)
        Deg_cost_coef_b: 0.005  # Coefficient of quadratic representation of degradation cost(pRT)
        Deg_cost_coef_c: 0.005  # Coefficient of quadratic representation of degradation cost(pRT)
        Loss_coef_a: 0.005  # Coefficient of linear representation of losses(pRT)
        Loss_coef_b: 0.005  # Coefficient of linear representation of losses(pRT)
        Available_Capacity: 286.125  # Initial energy capacity [kWh]
        Available_Power: 50  # Initial power capacity [kW]
        Maximum_SOC: 90  # Maximum allowed SOC [%]
        Minimum_SOC: 10  # Minimum allowed SOC [%]
Thermal_Storage_Units:
- PCM: 
    Key: 'PCM_ESS'  # File with the output power of the PCM
    Eta_ch: 0.7  # Charging efficiency
    Eta_dis: 0.7  # Discharging efficiency
    Static: 0  # Idling loss fraction from current SOE during one hour [-]
    Gamma: 1  # ??
    Loss_coef_a: 0.005  # Coefficient of linear representation of losses(pRT)
    Loss_coef_b: 0.005  # Coefficient of linear representation of losses(pRT)
    Available_Capacity: 1  # Initial energy capacity [kWh]
    Available_Power: 1  # Initial power capacity [kW]
    Maximum_SOC: 90  # Maximum allowed SOC [%]
    Minimum_SOC: 10  # Minimum allowed SOC [%]
Thermal_to_Electrical_Converters:
- Rankine_cycle:
    Key: 'RC_SPMp'
    Eta_RC: 0.36  # Efficiency of the Rankine cycle
Electrical_Generation_Units:
- Wind_Turbine:
    Key: 'WG_PPMp'  # File with the output power of the wind turbine
    Maintenance_Cost: 0.005  # Maintenance cost of the wind turbine
- Solar_PV:
    Key: 'PV_PPMp'  # File with the output power of the solar PV
    Maintenance_Cost: 0.005  # Maintenance cost of the solar PV
- Grid_Connection:
    Key: 'elExGRID'
    MAX_Power: 100  # Maximum power that can be drawn from the grid [kW]
    MIN_Power: -100  # Minimum power that can be drawn from the grid [kW]
Thermal_Generation_Units:
- Concentrated_Solar_Power:
    Key: 'CSP_MS_STPwtRK'  # File with the output power of the CSP
    Maintenance_Cost: 0.005  # Maintenance cost of the CSP
- Boiler:
    Key: 'Boiler_generator_power.csv'  # File with the output power of the boiler
    Maintenance_Cost: 0.005  # Maintenance cost of the boiler
- Tower_Solar:
    Key: 'TPS_MS_STPnoRK'  # File with the output power of the tower solar
    Maintenance_Cost: 0.005  # Maintenance cost of the tower solar
- Thermal_grid_connection:
    Key: 'thExGrid'
    MAX_Power: 100  # Maximum power that can be drawn from the grid [kW]
    MIN_Power: -100  # Minimum power that can be drawn from the grid [kW]

Electrical_Loads:
- EV:
    Key: 'CEV_SCp'  # File with the power of the CEV

-CPL:
    Key: 'CPl_SCp'  # File with the power of the CPL
-Cebu:
    Key: 'Cbue_NSCp'  # File with the power of the Cebu
-Cbu:
    Key: 'Cbu_NSCp'  # File with the power of the Cbu
Thermal_Loads:
- Ctbu:
    Key: 'Ctbu_TCp'  # File with the power of the Ctbu